# ******* PyTorch Fundamentals *******

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch

In [40]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [41]:
print(torch.__version__)

2.4.1+cu121


# Introduction to Tensors

In [42]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [43]:
print(scaler.ndim, scaler.item())

0 7


In [44]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [45]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [46]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [47]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [48]:
MATRIX[0]

tensor([7, 8])

In [49]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [50]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [51]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random Tensors

In [52]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.9386, 0.2579, 0.7713, 0.2604, 0.9479, 0.7826, 0.3522, 0.6350,
          0.2383, 0.8997],
         [0.1571, 0.6524, 0.8840, 0.9011, 0.1911, 0.5046, 0.0368, 0.1867,
          0.2481, 0.8518],
         [0.9033, 0.0830, 0.0086, 0.2418, 0.4534, 0.8397, 0.8872, 0.7216,
          0.5969, 0.1395],
         [0.7491, 0.5225, 0.3844, 0.9691, 0.4701, 0.3121, 0.0679, 0.1561,
          0.7903, 0.5522],
         [0.7787, 0.7486, 0.7355, 0.2689, 0.7879, 0.2798, 0.8806, 0.6694,
          0.6920, 0.2034],
         [0.5200, 0.5486, 0.8429, 0.4365, 0.3868, 0.8969, 0.3201, 0.3472,
          0.8720, 0.6787],
         [0.9120, 0.3236, 0.4644, 0.1791, 0.4075, 0.6865, 0.4657, 0.9325,
          0.3252, 0.8259],
         [0.4186, 0.7467, 0.4001, 0.4446, 0.9775, 0.3608, 0.0314, 0.0259,
          0.3114, 0.6108],
         [0.6982, 0.2642, 0.3986, 0.4517, 0.2880, 0.6125, 0.0433, 0.3086,
          0.5015, 0.7951],
         [0.2389, 0.6676, 0.0182, 0.6611, 0.5607, 0.6079, 0.0744, 0.3254,
          0.6892,

In [53]:
random_tensor.ndim, random_tensor.shape

(3, torch.Size([1, 10, 10]))

In [54]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.8983, 0.1714, 0.4430,  ..., 0.2785, 0.5530, 0.9442],
         [0.9463, 0.0702, 0.4503,  ..., 0.5285, 0.6618, 0.8190],
         [0.4536, 0.2837, 0.5158,  ..., 0.4398, 0.5290, 0.5661],
         ...,
         [0.5913, 0.6688, 0.7885,  ..., 0.7854, 0.4345, 0.5092],
         [0.1858, 0.8518, 0.0709,  ..., 0.7290, 0.4939, 0.3335],
         [0.0351, 0.1276, 0.4361,  ..., 0.5956, 0.2528, 0.2324]],

        [[0.6901, 0.0958, 0.6051,  ..., 0.3432, 0.9311, 0.9683],
         [0.1823, 0.7081, 0.1252,  ..., 0.5105, 0.4756, 0.1243],
         [0.5956, 0.4850, 0.9761,  ..., 0.9530, 0.8158, 0.1369],
         ...,
         [0.7693, 0.4413, 0.1066,  ..., 0.7615, 0.7829, 0.2680],
         [0.8883, 0.3123, 0.3205,  ..., 0.0174, 0.1394, 0.8187],
         [0.4091, 0.6497, 0.0356,  ..., 0.1413, 0.1690, 0.1285]],

        [[0.6638, 0.9568, 0.0022,  ..., 0.4380, 0.2564, 0.4188],
         [0.6803, 0.4147, 0.6980,  ..., 0.8567, 0.1319, 0.8638],
         [0.5432, 0.7050, 0.8830,  ..., 0.9811, 0.4427, 0.

In [ ]:
image = random_image_size_tensor.numpy().transpose(1, 2, 0)

# Display the image
plt.imshow(image)
plt.title("Random Image")
plt.axis("off")  # Turn off the axes
plt.show()

# Zeros and Ones

In [56]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [57]:
ones = torch.ones(size=(4, 5), dtype=torch.int8)
ones

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)

# Range of Tensors and Tensor Like

In [58]:
one_to_ten = torch.arange(1, 11, 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Finding out details about the tensor

1. DataTyoe
2. Size/Shape
3. Device

In [60]:
some_tensor = torch.rand([3, 4])
print(some_tensor)
print(f'DataType of tensor : {some_tensor.dtype}')
print(f'Shape of the tensor : {some_tensor.shape}')
print(f'Tensor is on device : {some_tensor.device}')

tensor([[6.2671e-01, 3.6499e-01, 3.3938e-01, 9.2094e-01],
        [2.6424e-01, 1.5963e-01, 3.2366e-01, 8.4347e-04],
        [8.3070e-01, 9.9119e-01, 3.8959e-01, 3.3953e-01]])
DataType of tensor : torch.float32
Shape of the tensor : torch.Size([3, 4])
Tensor is on device : cpu


# Tensor Operations

In [61]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10    # or torch.add(tensor, 10)

tensor([11, 12, 13])

In [62]:
# Multiplication (element wise)
tensor * 10    # or torch.mul(tensor, 10)

tensor([10, 20, 30])

In [63]:
# Subtraction
tensor - 10    # or torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [64]:
# Division
tensor/10      # or torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [65]:
# Matrix multiplication
print(tensor, '.', tensor+tensor, 'equals', sep=' ', end = ":")
torch.matmul(tensor, tensor+tensor)

tensor([1, 2, 3]) . tensor([2, 4, 6]) equals:

tensor(28)

In [66]:
a = torch.randint(10, size=(3, 4))
b = torch.randint(10, size=(4, 3))
print(a, '.\n', b, 'equals : ')
torch.matmul(a, b)

tensor([[4, 4, 9, 5],
        [8, 5, 9, 3],
        [8, 9, 7, 0]]) .
 tensor([[7, 3, 9],
        [0, 8, 0],
        [7, 4, 1],
        [5, 2, 1]]) equals : 


tensor([[116,  90,  50],
        [134, 106,  84],
        [105, 124,  79]])

# Min max argmin argmax

In [67]:
a.min(), torch.min(a)

(tensor(0), tensor(0))

In [68]:
a.max(), torch.max(a)

(tensor(9), tensor(9))

In [69]:
a.argmin(), torch.argmin(a)

(tensor(11), tensor(11))

In [70]:
a.argmax(), torch.argmax(a)

(tensor(2), tensor(2))

# Reshape, View, Squeezing, Unsqueezing, Stacking, Permuting 

In [71]:
x = a.reshape(1, 2, 3, 2)
x

tensor([[[[4, 4],
          [9, 5],
          [8, 5]],

         [[9, 3],
          [8, 9],
          [7, 0]]]])

In [72]:
x = a.view(3, 4)
x

tensor([[4, 4, 9, 5],
        [8, 5, 9, 3],
        [8, 9, 7, 0]])

In [88]:
x = torch.arange(1, 13, 1)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [89]:
x_reshaped = x.reshape(3, 4)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [90]:
z = x.view(1, 6, 2)
z

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [92]:
z[0, 0, 0] = 55
z, x      # Because the memory is shared.

(tensor([[[55,  2],
          [ 3,  4],
          [ 5,  6],
          [ 7,  8],
          [ 9, 10],
          [11, 12]]]),
 tensor([55,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [100]:
%%time
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

CPU times: user 863 µs, sys: 128 µs, total: 991 µs
Wall time: 706 µs


tensor([[55,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [55,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [55,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [55,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [99]:
%%time
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

CPU times: user 536 µs, sys: 0 ns, total: 536 µs
Wall time: 398 µs


tensor([[55, 55, 55, 55],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10],
        [11, 11, 11, 11],
        [12, 12, 12, 12]])

In [116]:
# Squeezing
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
y = torch.squeeze(x, 0)
print(y.size())
y = torch.squeeze(x, 1)
print(y.size())
y = torch.squeeze(x, (1, 2, 3))
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])
torch.Size([2, 2, 2])


In [130]:
x = torch.arange(1, 10, 1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [135]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [151]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [152]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [159]:
# Permute
x = torch.randint(high=10, size=(2, 3, 5))
print(x)
print(x.permute(0, 2, 1))
print(x.permute(0, 2, 1).shape)

tensor([[[5, 2, 2, 8, 0],
         [9, 0, 9, 8, 8],
         [3, 8, 6, 0, 4]],

        [[6, 7, 0, 8, 4],
         [0, 9, 4, 9, 4],
         [6, 0, 2, 4, 1]]])
tensor([[[5, 9, 3],
         [2, 0, 8],
         [2, 9, 6],
         [8, 8, 0],
         [0, 8, 4]],

        [[6, 0, 6],
         [7, 9, 0],
         [0, 4, 2],
         [8, 9, 4],
         [4, 4, 1]]])
torch.Size([2, 5, 3])


# Indexing 

In [175]:
import torch

x = torch.arange(1, 13)
print(x, x.shape)
x = x.reshape(1, 3, 4)
print(x, x.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]) torch.Size([12])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]) torch.Size([1, 3, 4])


In [176]:
x[0], x[0][0], x[0][0][0]

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 tensor([1, 2, 3, 4]),
 tensor(1))

In [177]:
x[0][1][2]

tensor(7)

In [178]:
x[0, 1, 2]

tensor(7)

In [181]:
x[:, :, 1]

tensor([[ 2,  6, 10]])

In [185]:
x[0, :, 0], x[:, :, 0]     # Shape is different

(tensor([1, 5, 9]), tensor([[1, 5, 9]]))

# NumPy Arrays and Torch Tensors

In [186]:
import torch
import numpy as np

In [187]:
array = np.arange(1, 8)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [188]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [189]:
numpy_tensor.dtype

dtype('float32')

# Reproducibilty (Trying to take out Random of Random)

In [200]:
import torch

RANDOM_SEED = 42

In [201]:
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)
random_tensor_A

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [202]:
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)
random_tensor_B

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [203]:
random_tensor_A == random_tensor_B

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Accessing a GPU

In [1]:
!nvidia-smi

Sat Jan  4 15:49:57 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla P100-PCIE-16GB           Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P0             27W /  250W |       0MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [5]:
# Counting the number of GPUs
torch.cuda.device_count()

1

# Putting Tensors and Models on GPU

In [6]:
# Creating a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3], device='cpu')
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor([1, 2, 3], device='cuda:0')


# Moving tensors back to CPU

> tensor_on_gpu.numpy()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-e0c96c7436fd> in <cell line: 1>()
----> 1 tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [13]:
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])